name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main # หรือ branch ที่คุณใช้ Deploy

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    # *** ADDED: กำหนดสิทธิ์ให้ GITHUB_TOKEN สำหรับ Job นี้ ***
    permissions:
      contents: write # จำเป็นสำหรับการเขียนไฟล์
      pages: write # จำเป็นสำหรับการจัดการ GitHub Pages
      id-token: write # จำเป็นสำหรับการใช้งาน OIDC เพื่อการ Deploy ที่ทันสมัย
    # *** END ADDED ***
    
    # ดึงค่า Environment Variables จาก Secrets หรือ Variables
    env:
      # ลองดึงจาก SECRETS ก่อน หากไม่มีค่า ให้ดึงจาก VARS
      BUILD_DRONE_ID: ${{ secrets.DRONE_ID || vars.DRONE_ID }}
      BUILD_API_BASE_URL: ${{ secrets.API_BASE_URL || vars.API_BASE_URL }}
      
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Show Environment Variables
        run: |
          echo "DRONE_ID from Environment: $BUILD_DRONE_ID"
          echo "API_BASE_URL from Environment: $BUILD_API_BASE_URL"

      - name: Perform Build-Time Variable Replacement
        run: |
          # แทนที่ DRONE_ID Placeholder (ไม่มี Single Quote เพื่อให้เป็น Integer)
          # sed -i 's/ข้อความที่ต้องการหา/ข้อความที่ต้องการแทนที่/g' ชื่อไฟล์
          sed -i "s|##DRONE_ID_PLACEHOLDER##|$BUILD_DRONE_ID|g" index.html
          
          # แทนที่ API_BASE_URL Placeholder (ยังคงใช้ Single Quote เพราะเป็น String)
          # ใช้ | เป็น delimiter แทน / เพื่อหลีกเลี่ยงปัญหา URL มีเครื่องหมาย /
          sed -i "s|##API_BASE_URL_PLACEHOLDER##|'$BUILD_API_BASE_URL'|g" index.html
        
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./ # Directory ที่มี index.html อยู่
          # ถ้า Deploy ไปที่ root ของ GH Pages (User Pages) ให้ตั้งค่า user_name และ user_email
          # user_name: 'github-actions[bot]'
          # user_email: 'github-actions[bot]@users.noreply.github.com'